spring:
  cloud:
    function:
      scan:
        packages: com.codependent.serverless.processor 
    stream:
      bindings:
        input:
          group: stream-processors
          destination: raw-events
        output: 
          destination: processed-events

server:
  port: 8181
